[package]
name = "ic"
version = "0.1.0"
edition = "2021"

[dependencies]
iceberg = { git = "https://github.com/risingwavelabs/iceberg-rust.git", rev = "82c63b3452379c6b9f361e1dc7df43e14ece72aa", features = [
    "storage-s3",
    "storage-gcs",
] }
thiserror = "2.0.11"
async-trait = "0.1.86"
parquet = { version = "53.2", features = ["async"] }
serde = { version = "1", features = ["rc"] }
datafusion = "45.0.0"
iceberg-datafusion = { git = "https://github.com/risingwavelabs/iceberg-rust.git", rev = "82c63b3452379c6b9f361e1dc7df43e14ece72aa" }
url = "2"
iceberg-catalog-sql = { git = "https://github.com/risingwavelabs/iceberg-rust.git", rev = "82c63b3452379c6b9f361e1dc7df43e14ece72aa"}
tokio = { version = "1", default-features = false}
sqlx = { version = "0.8.2", default-features = false, features = [
    "bigdecimal",
    "chrono",
    "json",
    "mysql",
    "postgres",
    "runtime-tokio-native-tls",
    "rust_decimal",
    "sqlite",
    "time",
    "uuid",
] }
futures = "0.3.17"
futures-async-stream = "0.2.9"
async-stream = "0.3.5"
