[workspace]
resolver = "2"
members = ["core", "prost", "services/compactor"]

# [lib]
# name = "ic"
# path = "src/lib.rs"

# [[bin]]
# name = "ic-compactor-server"
# path = "services/compactor/src/server.rs"

[workspace.dependencies]
iceberg = { git = "https://github.com/risingwavelabs/iceberg-rust.git", rev = "683fb89edeaf8d1baae69e1f376d68b92be1d496", features = [
    "storage-s3",
    "storage-gcs",
] }
async-trait = "0.1.86"
parquet = { version = "53.2", features = ["async"] }
prost = "0.12"
serde = { version = "1", features = ["rc"] }
thiserror = "2.0.11"
tonic = "0.11.0"
tokio = { version = "1", features = ["full"] }

ic-core = { path = "./core" }
ic-prost = { path = "./prost" }
ic-service-compactor = { path = "./services/compactor" }

prost-build = { version = "0.12" }
tonic-build = "0.11.0"
