[package]
name = "ic"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
iceberg = { workspace = true }
parquet = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
