[package]
name = "ic-service-compactor"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "compactor-server"
path = "src/bin/compactor-server.rs"

[dependencies]
async-trait = "0.1.86"
ic-prost = { workspace = true }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
tonic = { workspace = true }
tokio = { workspace = true }
