services:
  compactor:
    build:
      context: ../..
      dockerfile: docker/compactor/Dockerfile
    ports:
      - "7777:7777"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - RUST_LOG=info
    restart: unless-stopped 